name: Testing

on: push

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Git checkout
        uses: actions/checkout@v3

      - name: 💾 Install modules
        run: npm ci

      - name: 🧪 Testing
        run: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALLOWED_ORIGIN_DEV: ${{ secrets.ALLOWED_ORIGIN_DEV }}
          MONGODB_CONNECTION: ${{ secrets.MONGODB_CONNECTION }}
          ALLOWED_ORIGIN_PROD: ${{ secrets.ALLOWED_ORIGIN_PROD }}

